import type { Metadata } from "next";
//import { Raleway } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "../styles/globals.css";
import { Nav } from "@/ui/Nav";
import logo from "@/public/images/home/logo.png";

//const raleway = Raleway({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Pedro Braga Dev",
  icons: "@/public/images/home/logo.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="bg-black antialiased" >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
