import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/ui/Nav";

const raleway = Raleway({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Pedro Braga Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={raleway.className}>
      <body className="bg-black antialiased" >
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
